### ISSUE TITLE
Timing too tight for LaTeX presentation for me on Oct 7

### ISSUE THREAD

**Issue by michaelpacer** [thehackerwithin/berkeley#44]
Hi @katyhuff — So when I signed up for giving the LaTeX presentation, I hadn't realized how many deadlines for postdoc positions, grants and conferences were going to appear right at the beginning of October.

@jljones @paciorek would you be ok moving to another week? If not, I don't think I will be able to help prepare a talk with ya'll…But, I will do mini lightning talks on the more foundational/theoretical aspects of tex/LaTeX once my plate clears up a bit (since that's what I'd expected to cover… e.g., brief history of font formats, what metafont is, what TeX vs. LaTeX are, the glue and box model, &c.).

@stefanv, @rossbar or @chick are any of you able to swap (assuming @jljones and @paciorek can swap, of course)?

**Comment by paciorek** [comment]
I'm happy to move to a different time. In fact I'm not sure what I was
going to contribute anyway. I suspect most attendees will know some LaTeX,
so now sure what level/type of content we were thinking of here.

**Comment by jljones** [comment]
Hi,

I was going to have to take myself off the schedule also, because I won't have time to prepare a presentation for next week. I've also been called for Jury Duty next week so I may or may not be able to be there next week.

I agree that most people will probably know Latex, so I'm not sure what to contribute there. Perhaps substituting another topic would be more relevant?

Best,
Jennifer

**Comment by katyhuff** [comment]
Ok, no worries folks. So... let's see... BIDS is actually going to be
pretty sparse next week anyway, because there's a BIDS fellows retreat. So,
most of the BIDS fellows will be in Seattle.  Maybe we can just cancel it
and give folks the opportunity to come together and hack, if they want to,
with no scheduled talks.

Sound ok?

If so, I'll reflect that in the schedule. Any LaTeX tidbits can be
converted into lightning talks for the rest of the semester's lightning
talk openings... Woudl that work?

**Comment by jljones** [comment]
Sounds good to me.

**Comment by michaelpacer** [comment]
I'm on board!

**Comment by katyhuff** [comment]
Done.
